.TH flatmailer-smtpd 8
.SH NAME
flatmailer-smtpd \- sendmail emulator interface for flatmailer
.SH SYNOPSIS
.B flatmailer-smtpd
.SH DESCRIPTION
This program is a front end program for
.BR flatmailer-queue .
It is invoked by
.BR flatmailer-inject
when mail senders request a
.I sendmail \-bs
SMTP interface for sending email.  This program accepts SMTP protocol
on standard input.  On successful completion as far as the DATA command,
this program executes
.B flatmailer-queue
directly with the appropriate sender and recipients.
See the documentation for
.B flatmailer-queue
for details on how messages are queued.
.SH RETURN VALUE
Always exits 0.  Any errors are notified to the caller by SMTP extended error codes.
.SH SEE ALSO
flatmailer-queue(8)
