.TH flatmailer 7
.SH NAME
flatmailer \- Overview of flatmailer documentation
.SH INTRODUCTION
.B flatmailer
is a simple and secure relay-only mail transport agent.
.P
Documentation on how messages are reformatted and injected into the
queue can be found in
.BR flatmailer-inject (1).
Documentation on how messages are actually inserted into the queue can
be found in
.BR flatmailer-queue (8).
The process of sending queued messages is described in
.BR flatmailer-send (8).
.P
The following table lists all the control files used by
.BR flatmailer .
.P
.RS
.nf
.ta 5c
control file	used by
.I adminaddr	\fBflatmailer-dsn\fR, \fBflatmailer-queue
.I allmailfrom	\fBflatmailer-queue
.I defaultdomain	\fBflatmailer-dsn\fR, \fBflatmailer-inject
.I defaulthost	\fBflatmailer-dsn\fR, \fBflatmailer-inject
.I doublebounceto	\fBflatmailer-dsn
.I helohost	\fBflatmailer-send
.I idhost	\fBflatmailer-dsn\fR, \fBflatmailer-inject
.I maxpause	\fBflatmailer-send
.I me		\fBflatmailer-dsn\fR, \fBflatmailer-inject
.I pausetime	\fBflatmailer-send
.I remotes	\fBflatmailer-send
.I sendtimeout	\fBflatmailer-send
.fi
.RE
