#!/bin/sh

set -e

. /usr/share/debconf/confmodule
db_version 2.0
db_capb backup

if [ -e /etc/mailname ]; then
	db_set shared/mailname "`head -n1 /etc/mailname`"
else
	db_get shared/mailname
	if [ -z "$RET" ]; then
		db_set shared/mailname "`hostname --fqdn`"
	fi
fi
db_get shared/mailname; DOMAIN=`echo -n $RET | cut -s -d. -f2-`

if [ -e /etc/flatmailer/defaultdomain ]; then
	db_set flatmailer/defaultdomain "`head -n1 /etc/flatmailer/defaultdomain`"
else
	db_get flatmailer/defaultdomain
	if [ -z "$RET" ]; then
		db_set flatmailer/defaultdomain "$DOMAIN"
	fi
fi

if [ -e /etc/flatmailer/remotes ]; then
	# Replace newlines with :, then fix any extra : that might turn up.
	# db_set flatmailer/relayhost "`cat /etc/flatmailer/remotes | tr '\n' ':' | sed 's/::*/:/g;s/:$//'`"
	db_set flatmailer/relayhost `awk -vORS=" : " 'NF == 0 { next } \
					  $1 ~ /:/ && $1 ~ /^[0-9a-fA-F:]+(%[0-9a-z]+)?$/ \
					   	{ sub($1,"[&]",$0) } \
					  { print }' /etc/flatmailer/remotes | sed 's/ *: *$//'`
else
	db_get flatmailer/relayhost
	if [ -z "$RET" ]; then
		db_set flatmailer/relayhost "mail${DOMAIN:+.$DOMAIN}"
	fi
fi

if [ -e /etc/flatmailer/adminaddr ]; then
	db_set flatmailer/adminaddr "`head -n1 /etc/flatmailer/adminaddr`"
else
	db_get flatmailer/adminaddr
fi

state=1
while [ "$state" -ge 1 -a "$state" -le 3 ]; do
	case "$state" in
	1)	db_input high shared/mailname || true
		;;
	2)	db_input high flatmailer/relayhost || true
		;;
	3)	db_input medium flatmailer/adminaddr || true
		;;
	esac
	if db_go; then
		state=$(($state + 1))
	else
		state=$(($state - 1))
	fi
done

db_stop
exit 0
