#! /bin/sh

set -e

case "$1" in
       purge)

		rm -f \
			/etc/flatmailer/defaultdomain \
			/etc/flatmailer/defaultdomain.dpkg-* \
			/etc/flatmailer/remotes \
			/etc/flatmailer/remotes.dpkg-* \
			/etc/flatmailer/adminaddr \
			/etc/flatmailer/adminaddr.dpkg-* \
			/etc/flatmailer/defaulthost \
			/etc/flatmailer/defaulthost.dpkg-*

        ;;

esac

#DEBHELPER#

exit 0
