#! /bin/sh
# postinst script for flatmailer
#
# see: dh_installdeb(1)

set -e

. /usr/share/debconf/confmodule
db_version 2.0

umask 022

case "$1" in
    configure|reconfigure)

		db_get shared/mailname
		echo "$RET" > /etc/mailname

		db_get flatmailer/defaultdomain
		if [ "$RET" ]; then
			echo "$RET" > /etc/flatmailer/defaultdomain
		else
			echo -n > /etc/flatmailer/defaultdomain
		fi

		db_get flatmailer/relayhost
		# securely create flatmailer/remotes with mode 0600
		if [ ! -e /etc/flatmailer/remotes ]
		then
			M=$( umask )
			umask 077
			> /etc/flatmailer/remotes
			chown mail:mail /etc/flatmailer/remotes
			umask $M
		fi
		echo "$RET" | sed -r -e ':a s/(\[[^]:]*):/\1=/; ta' \
				     -e 's/[[:space:]]*:[[:space:]]*/\n/g' \
				     -e ':b s/(\[[^]=]*)=/\1:/; tb' \
				     -e 's/[][]//g' > /etc/flatmailer/remotes
		# zap debconf entry, as this key may contain sensitive data.
		db_set flatmailer/relayhost ""

		db_get flatmailer/adminaddr
		if [ "$RET" ]; then
			echo "$RET" > /etc/flatmailer/adminaddr
		else
			echo -n > /etc/flatmailer/adminaddr
		fi

		db_stop

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
